# Site settings
title: Big Three Club
email: admin@bigthree.club
description: > # this means to ignore newlines until "baseurl:"
  Your destination for daily Big Three information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bigthree.club" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
